# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    product.listener:
        class: AppBundle\EventListener\ProductListener
        arguments: ["@mailer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
